<?php

namespace Acme\ReginaldBundle\Repository;

/**
 * OutputRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutputRepository extends \Doctrine\ORM\EntityRepository
{
}
